//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WriteLogKeyProcessor {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "10.0.0.0")]
    internal sealed partial class KeyProcessorSettings : global::System.Configuration.ApplicationSettingsBase {
        
        private static KeyProcessorSettings defaultInstance = ((KeyProcessorSettings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new KeyProcessorSettings())));
        
        public static KeyProcessorSettings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public double[] AllowedBandsRadio1 {
            get {
                return ((double[])(this["AllowedBandsRadio1"]));
            }
            set {
                this["AllowedBandsRadio1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public double[] AllowedBandsRadio2 {
            get {
                return ((double[])(this["AllowedBandsRadio2"]));
            }
            set {
                this["AllowedBandsRadio2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public double[] AllowedBandsRadio3 {
            get {
                return ((double[])(this["AllowedBandsRadio3"]));
            }
            set {
                this["AllowedBandsRadio3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public double[] AllowedBandsRadio4 {
            get {
                return ((double[])(this["AllowedBandsRadio4"]));
            }
            set {
                this["AllowedBandsRadio4"] = value;
            }
        }
    }
}
